new input values
diedekerkhof/Regels pull request #1
Opened 2022-11-24 08:23 UTC by sgort

Ondanks de wijziging krijg ik nog steeds de oude waardes in de frontend getoond.
![image](https://user-images.githubusercontent.com/25812095/203730454-3e2345d1-6d7a-4b6b-bf24-834df42aa336.png)

2022-11-24 09:12 UTC, sgort commented
Ondanks de nieuwe dataset krijg ik óók nog de oude terug in de frontend...

![image](https://user-images.githubusercontent.com/25812095/203743755-408a37fc-f95e-4c4e-9b57-11a3a9c7fc1b.png)

2022-11-24 09:13 UTC, sgort commented
Heb achtereenvolgens stop en restart gedaan ná commit nieuwe data

2022-11-24 09:15 UTC, diedekerkhof commented
Als je aan de frontend wilt ontwikkelen moet je de frontend los draaien of deze builden. Ik had hiervoor een readme in het de frontend folder staan maar die heeft git volgens mij weggegooid. Ik zal iets toevoegen in de Readme.

2022-11-24 09:19 UTC, diedekerkhof commented
Je ziet de oude data nog omdat die nog in de database staat. Je hebt een changeset toegevoegd in de databaseChangeLog maar de stap die ervoor staat (mijn inserts) blijft er ook in. Als je die data weg wilt hebben kan je een delete toevoegen in de databaseChangeLog. 

Let er wel op dat als je niet oude changeSets aan kan passen, anders krijg je een error.  Een workaround zou zijn om een delete tussen onze inserts toe te voegen en de h2 database weg te gooien.
Dit kan in de frankrunner folder op frank-runner\build\h2\v2.

2022-11-24 09:28 UTC, diedekerkhof commented on src/main/configurations/RegelsAPI/DatabaseChangelog.xml
> +
Als je de database leeg wilt hebben voeg dan hier dit toe

`<changeSet id="delete-data" author="Diede Kerkhof">  
    <delete 
            tableName="REGELS"> 
    </delete>
</changeSet>`

Hiervoor moet je wel de h2 database resetten, doe dit door de files in deze map weg te gooien: frank-runner\build\h2\v2\

2022-11-24 11:23 UTC, sgort commented
Please have a look naar wat ik fout doe.

- als ik `main` branch start met lege h2 db folder, dan werkt het zoals verwacht
- als ik `config-changes` branch start met lege h2 db folder, dan krijg ik geen enkel resultaat bij zoeken.

Mijn insert ná de delete is nagenoeg gelijk aan jouw versie, met enkel afwijking op `REGELING_NAME` en `REGELING_EXECUTIE`.

2022-11-24 11:24 UTC, diedekerkhof requested changes

2022-11-24 11:24 UTC, diedekerkhof commented on src/main/configurations/RegelsAPI/DatabaseChangelog.xml
> +	<!--This requires h2 database reset. Delete the files in: frank-runner\build\h2\v2\ -->
dit is alleen nodig als iemand al eerder de database gestart heeft, ik neem aan dat voor de rest niemand dat heeft gedaan dus deze regel kan weg

2022-11-28 10:36 UTC, sgort commented
> Als je aan de frontend wilt ontwikkelen moet je de frontend los draaien of deze builden. Ik had hiervoor een readme in het de frontend folder staan maar die heeft git volgens mij weggegooid. Ik zal iets toevoegen in de Readme.

Deze Readme ontbreekt nog. Klopt dat?

2022-11-28 14:19 UTC, diedekerkhof commented
Het staat nu in de readme in de main branch

2022-11-28 14:19 UTC, diedekerkhof approved these changes

2022-11-28 14:19 UTC, merged